services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: elogap-ui-dev
    ports:
      - '5173:5173'
    volumes:
      - ./ui:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
    networks:
      - elogapnet
    working_dir: /app
    command: ["pnpm", "dev", "--host", "0.0.0.0"]
    
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: elogap-api-dev
    # depends_on:
    env_file:
      - .env
    environment:
      - PORT=${API_PORT}
      - APP_ENV=${APP_ENV}
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["air", "-c", ".air.toml"]

networks:
  elogapnet:
    driver: bridge